FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY server /app
RUN go build -o qssh-server

FROM alpine:3.22

RUN apk add --no-cache openssh
RUN adduser -D -s /bin/sh testuser
RUN echo 'testuser:testpass' | chpasswd
RUN mkdir -p /etc/qssh

RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN ssh-keygen -A

COPY --from=builder /app/qssh-server /usr/local/bin/qssh-server
COPY testdata/config.toml /etc/qssh/config.toml
COPY testdata/config-mtls.toml /etc/qssh/config-mtls.toml

COPY testdata/server.crt /etc/qssh/server.crt
COPY testdata/server.key /etc/qssh/server.key
COPY testdata/ca.crt /etc/qssh/ca.crt
COPY testdata/entrypoint.sh /start.sh

RUN chmod +x /start.sh

EXPOSE 22 4433/udp

ENTRYPOINT ["/start.sh"]
CMD ["/etc/qssh/config.toml"]
